version: '3.8'

services:
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"

  # app:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile
  #   container_name: dex-monitor-app
  #   working_dir: /usr/src/app
  #   volumes:
  #     - ../:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - redis
  #   environment:
  #     REDIS_URL: "redis://localhost:6379"
  #     PORT: "3000"
